services:
  ehr-sandbox:
    image:
      clemhen/ehr-sandbox:proxy-fhir-test-6
    container_name: ehr-sandbox-gyro
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data-h2/ehr;
    restart: unless-stopped
    volumes:
      - ehr-h2-data:/data-h2
    ports:
      #     Default port is 9091, can be changed here
      - "9091:8080"

volumes:
  #  sandbox-mysql:
  ehr-h2-data: