package org.immregistries.ehr.shlink.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.jsonwebtoken.CompressionException;
import io.jsonwebtoken.Jwt;
import io.jsonwebtoken.Jwts;
import org.immregistries.ehr.api.security.JwtUtils;
import org.immregistries.ehr.shlink.model.ShCardClaims;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;

import java.security.PublicKey;
import java.util.Base64;
import java.util.stream.IntStream;
import java.util.zip.DataFormatException;

import static org.immregistries.ehr.shlink.SmartHealthConstants.SH_CARD_PREFIX;
import static org.immregistries.ehr.shlink.SmartHealthConstants.SMALLEST_B64_CHAR_CODE;

@Service
public class SmartHealthCardParser {
    private static final Logger logger = LoggerFactory.getLogger(SmartHealthCardParser.class);

    @Autowired
    private JwtUtils jwtUtils;

    private Gson gson = new Gson();
    private ObjectMapper objectMapper = new ObjectMapper();


    public ShCardClaims.VerifiableCredential parseVCFromCompactJwt(Authentication authentication, String compact) throws JsonProcessingException {
        PublicKey publicKey = jwtUtils.getUserPublicKey(authentication);
        return parseVCFromCompactJwt(publicKey, compact);
    }

    public ShCardClaims.VerifiableCredential parseVCFromCompactJwt(PublicKey publicKey, String compact) throws CompressionException, JsonProcessingException {
        logger.info("Parsing compact {}\n\n", compact);
        // Tells Jackson that "1776924536" is in nanoseconds (JWT standard)
        objectMapper.configure(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS, true);

        if (publicKey != null) {
            Jwt jws = Jwts.parser().verifyWith(publicKey).build().parseSignedClaims(compact);
            String jsonPayload = gson.toJson(jws.getPayload());
            ShCardClaims shCardClaims = objectMapper.readValue(jsonPayload, ShCardClaims.class);
            return shCardClaims.getVerifiableCredential();
        } else {
            throw new RuntimeException("Key not found");
        }
    }


    public ShCardClaims.VerifiableCredential parseVCFromCompactJwtUnsecure(String compact) throws JsonProcessingException {
        String[] chunks = compact.split("\\.");
        Base64.Decoder decoder = Base64.getUrlDecoder();
        JsonObject header = JsonParser.parseString(new String(decoder.decode(chunks[0]))).getAsJsonObject();
//        logger.info("header {}", header);
        byte[] payload = decoder.decode(chunks[1]);
        String payloadString;
        if (header.has("zip") && header.get("zip").getAsString().equalsIgnoreCase("DEF")) {
            String result;
            try {
                result = new String(CompressionUtil.inflate(payload));
            } catch (DataFormatException e) {
                throw new RuntimeException(e);
            }
            payloadString = result;
        } else {
            payloadString = new String(payload);
        }
        ObjectMapper objectMapper = new ObjectMapper();

        ShCardClaims shCardClaims = objectMapper.readValue(payloadString, ShCardClaims.class);
        return shCardClaims.getVerifiableCredential();
    }

    public String qrCodeRead(String shc) {
        if (!shc.startsWith(SH_CARD_PREFIX)) {
            throw new RuntimeException("Not a SmartHealthCard");
        }
        String encodedForQrCode = shc.substring(shc.lastIndexOf("/") + 1);
        String decodedFromQrCode = getDecodedFromQrCode(encodedForQrCode);
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            ObjectMapper objectMapper = new ObjectMapper();
            ShCardClaims.VerifiableCredential verifiableCredential = parseVCFromCompactJwt(authentication, decodedFromQrCode);
            return objectMapper.writer().writeValueAsString(verifiableCredential);
        } catch (Exception e) {
            throw new RuntimeException("Failed to Read Qr Code " + decodedFromQrCode, e);
        }
    }


    private static String getDecodedFromQrCode(String encodedForQrCode) {
        // TODO verify this part, generated by LLM
        String decodedFromQrCode = IntStream.range(0, encodedForQrCode.length() / 2)
                .map(i -> {
                    String pair = encodedForQrCode.substring(i * 2, i * 2 + 2);
                    int integer = Integer.parseInt(pair);
                    return (char) (integer + SMALLEST_B64_CHAR_CODE);
                })
                .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
                .toString();
        return decodedFromQrCode;
    }

}
