#logging.level.org.hibernate.SQL: DEBUG
spring:
  config.import: optional:file:.env[.properties]
  #  main.web-application-type: none
  datasource:
    username: ${ENV_EHR_DATASOURCE_USER}
    password: ${ENV_EHR_DATASOURCE_PASSWORD}
    #    url: jdbc:h2:mem:ehr-test;
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: org.h2.Driver
  #  h2:
  #    console.enabled: true
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
# App Properties
ehr:
  api:
    app:
      jwtSecret: ${ENV_EHR_JWT_SECRET:}
      jwtExpirationMs: 86400000
#spring.output.ansi.enabled:always

server:
  servlet:
    contextPath: ${SERVER_SERVLET_CONTEXT_PATH:/ehr}
