#spring.jpa.hibernate.ddl-auto:none
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
spring:
  #  main.web-application-type: none
  profiles.active: '@activatedProperties@'
  datasource:
    #    url : "jdbc:mysql://localhost:3306/ehr"
    username: 'ehr_web'
    password: 'SharkBaitHooHaHa'
    url: jdbc:h2:mem:ehr-test;
    #    url: jdbc:h2:file:./data-h2/ehr;MODE=MYSQL;FILE_LOCK=FILE;AUTO_SERVER=TRUE;
    driverClassName: org.h2.Driver
  #  h2:
  #    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      #      use-new-id-generator-mappings: false
      #      id.new_generator_mappings: false
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
  #    properties:
  #      hibernate:
  #        show_sql: true
  #        use_sql_comments: true
  #        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
# App Properties
ehr:
  api:
    app:
      jwtSecret: EHRSandboxSecretKeythebigshortwquefvkqiywubflqieflhi3iBINSDFqwflquwehbk327872ihgrsog8y742ui3o2fkmejnrgb2og3q92pefiovbuqilogr3huf2peonu2r6w7ueh3vhuwd68w7ygv4fbhgn[]f[wegrnewbrgyu';fjrbw1utfir16firtfuyuyqwyefyqey2276363g8fg8g2f
      jwtExpirationMs: 86400000
#spring.output.ansi.enabled:always

---
spring.config.activate.on-profile: dev
server:
  servlet:
    contextPath: /ehr


---
spring.config.activate.on-profile: prod
