#logging.level.org.hibernate.SQL: DEBUG
spring:
  config.import: optional:file:.env[.properties]
  #  main.web-application-type: none
  profiles.active: '@activatedProperties@'
  datasource:
    username: ${ENV_EHR_DATASOURCE_USER}
    password: ${ENV_EHR_DATASOURCE_PASSWORD}
    #    url: jdbc:h2:mem:ehr-test;
    url: jdbc:h2:file:./data-h2/ehr;
    driverClassName: org.h2.Driver
  #  h2:
  #    console.enabled: true
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
# App Properties
ehr:
  api:
    app:
      jwtSecret: ${ENV_EHR_JWT_SECRET}
      jwtExpirationMs: 86400000
#spring.output.ansi.enabled:always

---
spring.config.activate.on-profile: dev
server:
  servlet:
    contextPath: /ehr


---
spring.config.activate.on-profile: prod
