#spring.jpa.hibernate.ddl-auto:none
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
hapi:
  fhir:
    fhir_version: R5
spring:
  profiles.active: '@activatedProperties@'
  datasource:
    url : "jdbc:mysql://localhost:3306/ehr"
    username : 'ehr_web'
    password : 'SharkBaitHooHaHa'
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
    hibernate:
      use-new-id-generator-mappings: false
# App Properties
ehr:
  api:
    app:
      jwtSecret: EHRSandboxSecretKeythebigshortwquefvkqiywubflqieflhi3iBINSDFqwflquwehbk327872ihgrsog8y742ui3o2fkmejnrgb2og3q92pefiovbuqilogr3huf2peonu2r6w7ueh3vhuwd68w7ygv4fbhgn[]f[wegrnewbrgyu';fjrbw1utfir16firtfuyuyqwyefyqey2276363g8fg8g2f
      jwtExpirationMs: 86400000
#spring.output.ansi.enabled:always

---
spring.config.activate.on-profile: dev
server:
  port: 9091
  server.contextPath: /ehr


---
spring.config.activate.on-profile: prod
